version: "3.9"
services:
  demo-app:
    build:
      context: ../../..
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    links:
      - "quartzmanager-usecase-db:quartzmanager-usecase-db"
    volumes:
      - ./application.yml:/usr/app/quartz-manager-web-showcase/src/main/resources/application.yml
    networks:
      - backend

  quartzmanager-usecase-db:
    container_name: "quartzmanager"
    image: postgres:14.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: quartzmanager
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - backend

networks:
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
